// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UstediPametno.Data;

#nullable disable

namespace UstediPametno.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260829091625_DodaniBedzevi")]
    partial class DodaniBedzevi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UstediPametno.Models.Bedz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ikona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Vrsta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bedz", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ikona = "🌱",
                            Naziv = "Prvi korak",
                            Opis = "Ušteđeno prvih 100 KM",
                            Prag = 100m,
                            Vrsta = 0
                        },
                        new
                        {
                            Id = 2,
                            Ikona = "🪵",
                            Naziv = "Drveni štediša",
                            Opis = "Ušteđeno 500 KM",
                            Prag = 500m,
                            Vrsta = 0
                        },
                        new
                        {
                            Id = 3,
                            Ikona = "🥉",
                            Naziv = "Bronzani štediša",
                            Opis = "Ušteđeno 1.000 KM",
                            Prag = 1000m,
                            Vrsta = 0
                        },
                        new
                        {
                            Id = 4,
                            Ikona = "🥈",
                            Naziv = "Srebreni štediša",
                            Opis = "Ušteđeno 2.500 KM",
                            Prag = 2500m,
                            Vrsta = 0
                        },
                        new
                        {
                            Id = 5,
                            Ikona = "🥇",
                            Naziv = "Zlatni štediša",
                            Opis = "Ušteđeno 5.000 KM",
                            Prag = 5000m,
                            Vrsta = 0
                        },
                        new
                        {
                            Id = 6,
                            Ikona = "💎",
                            Naziv = "Dijamantni štediša",
                            Opis = "Ušteđeno 10.000 KM",
                            Prag = 10000m,
                            Vrsta = 0
                        },
                        new
                        {
                            Id = 7,
                            Ikona = "🌱",
                            Naziv = "Mjesec dana s nama",
                            Opis = "Član aplikacije najmanje 1 mjesec",
                            Prag = 1m,
                            Vrsta = 1
                        },
                        new
                        {
                            Id = 8,
                            Ikona = "🤝",
                            Naziv = "Vjerni član",
                            Opis = "Član aplikacije najmanje 3 mjeseca",
                            Prag = 3m,
                            Vrsta = 1
                        },
                        new
                        {
                            Id = 9,
                            Ikona = "⭐",
                            Naziv = "Pola godine s nama",
                            Opis = "Član aplikacije najmanje 6 mjeseci",
                            Prag = 6m,
                            Vrsta = 1
                        },
                        new
                        {
                            Id = 10,
                            Ikona = "🎂",
                            Naziv = "Godinu dana s nama",
                            Opis = "Član aplikacije najmanje 12 mjeseci",
                            Prag = 12m,
                            Vrsta = 1
                        });
                });

            modelBuilder.Entity("UstediPametno.Models.CiljStednje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CiljaniIznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumZavrsetka")
                        .HasColumnType("datetime2");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TrenutnoUstedjeno")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("CiljStednje", (string)null);
                });

            modelBuilder.Entity("UstediPametno.Models.FiksniTrosak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<bool>("JeAktivan")
                        .HasColumnType("bit");

                    b.Property<int>("Kategorija")
                        .HasColumnType("int");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MjesecniIznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("FiksniTrosak", (string)null);
                });

            modelBuilder.Entity("UstediPametno.Models.IzvorPrihoda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MjesecniIznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("IzvorPrihoda", (string)null);
                });

            modelBuilder.Entity("UstediPametno.Models.Korisnik", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("UstediPametno.Models.KorisnikBedz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedzId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumOsvajanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BedzId");

                    b.HasIndex("KorisnikId", "BedzId")
                        .IsUnique();

                    b.ToTable("KorisnikBedz", (string)null);
                });

            modelBuilder.Entity("UstediPametno.Models.MjesecniPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CiljStednjeId")
                        .HasColumnType("int");

                    b.Property<decimal>("DnevniBudzet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Mjesec")
                        .HasColumnType("int");

                    b.Property<decimal>("PotrebnaStednja")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrenesenoIzPrethodnogMjeseca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RaspolozivoZaTrosenje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StvarnoPotroseno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StvarnoUstedjeno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UkupanPrihod")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UkupniFiksniTroskovi")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CiljStednjeId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("MjesecniPlan", (string)null);
                });

            modelBuilder.Entity("UstediPametno.Models.MjesecniPlanCilj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CiljStednjeId")
                        .HasColumnType("int");

                    b.Property<int>("MjesecniPlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("PlaniraniIznos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CiljStednjeId");

                    b.HasIndex("MjesecniPlanId");

                    b.ToTable("MjesecniPlanCilj", (string)null);
                });

            modelBuilder.Entity("UstediPametno.Models.Transakcija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CiljStednjeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KorisnikId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MjesecniPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vrsta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CiljStednjeId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("MjesecniPlanId");

                    b.ToTable("Transakcija", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UstediPametno.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UstediPametno.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UstediPametno.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UstediPametno.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UstediPametno.Models.CiljStednje", b =>
                {
                    b.HasOne("UstediPametno.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("UstediPametno.Models.FiksniTrosak", b =>
                {
                    b.HasOne("UstediPametno.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("UstediPametno.Models.IzvorPrihoda", b =>
                {
                    b.HasOne("UstediPametno.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("UstediPametno.Models.KorisnikBedz", b =>
                {
                    b.HasOne("UstediPametno.Models.Bedz", "Bedz")
                        .WithMany()
                        .HasForeignKey("BedzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UstediPametno.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bedz");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("UstediPametno.Models.MjesecniPlan", b =>
                {
                    b.HasOne("UstediPametno.Models.CiljStednje", "CiljStednje")
                        .WithMany()
                        .HasForeignKey("CiljStednjeId");

                    b.HasOne("UstediPametno.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CiljStednje");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("UstediPametno.Models.MjesecniPlanCilj", b =>
                {
                    b.HasOne("UstediPametno.Models.CiljStednje", "CiljStednje")
                        .WithMany()
                        .HasForeignKey("CiljStednjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UstediPametno.Models.MjesecniPlan", "MjesecniPlan")
                        .WithMany("Ciljevi")
                        .HasForeignKey("MjesecniPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CiljStednje");

                    b.Navigation("MjesecniPlan");
                });

            modelBuilder.Entity("UstediPametno.Models.Transakcija", b =>
                {
                    b.HasOne("UstediPametno.Models.CiljStednje", "CiljStednje")
                        .WithMany()
                        .HasForeignKey("CiljStednjeId");

                    b.HasOne("UstediPametno.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UstediPametno.Models.MjesecniPlan", "MjesecniPlan")
                        .WithMany()
                        .HasForeignKey("MjesecniPlanId");

                    b.Navigation("CiljStednje");

                    b.Navigation("Korisnik");

                    b.Navigation("MjesecniPlan");
                });

            modelBuilder.Entity("UstediPametno.Models.MjesecniPlan", b =>
                {
                    b.Navigation("Ciljevi");
                });
#pragma warning restore 612, 618
        }
    }
}
